import { ClinicDoctor, ClinicProfile } from "./api";

const defaultHours = {
  weekdays: { start: "09:00", end: "18:00" },
  weekend: { start: "10:00", end: "14:00" },
  closedDays: ["Wednesday"],
  slotMinutes: 30,
};

const defaultPricing = {
  firstVisit: "¥3,000",
  followUp: "¥1,500",
  otherServices: "PCR test ¥6,000, Vaccination ¥4,500",
};

const defaultPhotos = (image: string) => [
  { label: "Waiting room", url: image },
  { label: "Reception", url: image },
  { label: "Exam room", url: image },
];

export const CLINIC_SEED: ClinicProfile[] = [
  {
    id: "noguchi",
    name: "Noguchi Hospital",
    type: "Hospital",
    rating: 3.9,
    patients: "10K+ patients",
    distance: "12 km away",
    location: "Aoyamacho, Beppu",
    image:
      "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80",
    specializations: [
      "Cardiologist",
      "Cardiology",
      "Gastroenterology",
      "Neurology",
      "Pulmonology",
      "General Physician",
      "General Medicine",
      "Internal Medicine",
      "Nephrology",
    ],
    nextAvailability: "Today, 4:30 PM",
    googlePlaceId: "ChIJM0fLQOamRjURHBffbpcNZkE",
    phone: "0977-22-1111",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "beppu-medical",
    name: "Beppu Medical Center",
    type: "Clinic",
    rating: 4.5,
    patients: "4K+ patients",
    distance: "8 km away",
    location: "Beppu Station",
    image:
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=800&q=80",
    specializations: [
      "Cardiologist",
      "Cardiology",
      "Dermatologist",
      "Dermatology",
      "Orthopedic Surgeon",
      "Orthopedics",
      "Endocrinology",
      "Allergy & Immunology",
    ],
    nextAvailability: "Today, 6:10 PM",
    googlePlaceId: "ChIJMwMNc4cdRDURX6Vpl9bGXS4",
    phone: "0977-25-2233",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "oita-ent",
    name: "Oita ENT & Hearing",
    type: "Clinic",
    rating: 4.8,
    patients: "2.3K patients",
    distance: "6 km away",
    location: "Kitahama, Beppu",
    image:
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
    specializations: ["ENT", "Otolaryngology", "Pulmonology"],
    nextAvailability: "Tomorrow, 10:00 AM",
    googlePlaceId: "ChIJ34f2cpqjRjURkxVuzkU3RPw",
    phone: "0977-33-4455",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "harbor-derma",
    name: "Harbor Dermatology",
    type: "Clinic",
    rating: 4.2,
    patients: "1.1K patients",
    distance: "4 km away",
    location: "Minami Beppu",
    image:
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=800&q=80",
    specializations: ["Dermatologist", "Dermatology"],
    nextAvailability: "Tomorrow, 1:15 PM",
    phone: "0977-18-2299",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "ap-house-family",
    name: "AP House Family Care",
    type: "Hospital",
    rating: 4.1,
    patients: "7.2K patients",
    distance: "2 km away",
    location: "Jumonjibaru, Beppu",
    image:
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    specializations: [
      "General Physician",
      "General Medicine",
      "Pediatrician",
      "Pediatrics",
      "Gynecology",
      "Internal Medicine",
    ],
    nextAvailability: "Today, 5:20 PM",
    phone: "0977-29-5566",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "sakura-ortho",
    name: "Sakura Ortho & Rehab",
    type: "Clinic",
    rating: 4.7,
    patients: "3.4K patients",
    distance: "10 km away",
    location: "Higashi Beppu",
    image:
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
    specializations: [
      "Orthopedic Surgeon",
      "Orthopedics",
      "Rheumatology",
      "General Physician",
      "General Medicine",
      "Sports Medicine",
      "Physical Therapy",
    ],
    nextAvailability: "Tomorrow, 9:40 AM",
    phone: "0977-20-7788",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "sunrise-peds",
    name: "Sunrise Children's Clinic",
    type: "Clinic",
    rating: 4.6,
    patients: "5.1K patients",
    distance: "5 km away",
    location: "Ishigaki, Beppu",
    image:
      "https://images.unsplash.com/photo-1484980972926-edee96e0960d?auto=format&fit=crop&w=800&q=80",
    specializations: ["Pediatrician", "Pediatrics"],
    nextAvailability: "Today, 3:00 PM",
    phone: "0977-27-8899",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1484980972926-edee96e0960d?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "bluewave-gastro",
    name: "Bluewave Digestive Center",
    type: "Clinic",
    rating: 4.4,
    patients: "3.1K patients",
    distance: "7 km away",
    location: "Beppu Bayfront",
    image:
      "https://images.unsplash.com/photo-1504439904031-93ded9f93e3c?auto=format&fit=crop&w=800&q=80",
    specializations: ["Gastroenterology"],
    nextAvailability: "Tomorrow, 11:20 AM",
    phone: "0977-11-4400",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1504439904031-93ded9f93e3c?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "beacon-neuro",
    name: "Beacon Neurology Institute",
    type: "Hospital",
    rating: 4.9,
    patients: "8.5K patients",
    distance: "14 km away",
    location: "Oita City",
    image:
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
    specializations: ["Neurology"],
    nextAvailability: "Tomorrow, 2:00 PM",
    phone: "0977-15-6677",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "serenity-mental",
    name: "Serenity Mental Health",
    type: "Clinic",
    rating: 4.3,
    patients: "2.8K patients",
    distance: "3 km away",
    location: "Downtown Beppu",
    image:
      "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=800&q=80",
    specializations: ["Psychiatry", "Psychology"],
    nextAvailability: "Today, 7:15 PM",
    phone: "0977-09-9900",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "clearview-eye",
    name: "Clearview Eye Hospital",
    type: "Hospital",
    rating: 4.6,
    patients: "6.7K patients",
    distance: "9 km away",
    location: "Kamegawa, Beppu",
    image:
      "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80",
    specializations: ["Ophthalmology"],
    nextAvailability: "Tomorrow, 8:45 AM",
    phone: "0977-77-1212",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "koyo-endo",
    name: "Koyo Endocrine & Diabetes",
    type: "Clinic",
    rating: 4.4,
    patients: "3.9K patients",
    distance: "11 km away",
    location: "Harumi, Beppu",
    image:
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=800&q=80",
    specializations: ["Endocrinology", "Diabetology"],
    nextAvailability: "Today, 2:20 PM",
    phone: "0977-66-5533",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=800&q=80",
    ),
  },
  {
    id: "harbor-womens",
    name: "Harbor Women's Care",
    type: "Clinic",
    rating: 4.5,
    patients: "2.1K patients",
    distance: "3 km away",
    location: "Harbor District, Beppu",
    image:
      "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=800&q=80",
    specializations: ["Gynecology", "Women's Health"],
    nextAvailability: "Today, 5:50 PM",
    phone: "0977-33-7788",
    hours: defaultHours,
    pricing: defaultPricing,
    photos: defaultPhotos(
      "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=800&q=80",
    ),
  },
];

const defaultAvailability = [
  {
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    startTime: "09:00",
    endTime: "18:00",
  },
];

export const DOCTOR_SEED: ClinicDoctor[] = [
  {
    id: "dr-ayanami",
    name: "Dr. Riko Ayanami",
    clinicId: "noguchi",
    specialization: "Cardiology",
    languages: ["Japanese", "English"],
    rating: 4.7,
    nextAvailable: "Today, 4:30 PM",
    availability: defaultAvailability,
  },
  {
    id: "dr-carter",
    name: "Dr. Lina Carter",
    clinicId: "noguchi",
    specialization: "Cardiology",
    languages: ["English", "Korean"],
    rating: 4.5,
    nextAvailable: "Today, 6:00 PM",
    availability: defaultAvailability,
  },
  {
    id: "dr-watanabe",
    name: "Dr. Taro Watanabe",
    clinicId: "beppu-medical",
    specialization: "Cardiology",
    languages: ["Japanese", "English"],
    rating: 4.8,
    nextAvailable: "Tomorrow, 9:15 AM",
    availability: defaultAvailability,
  },
  {
    id: "dr-chen",
    name: "Dr. Mei Chen",
    clinicId: "beppu-medical",
    specialization: "Dermatology",
    languages: ["Mandarin", "English"],
    rating: 4.6,
    nextAvailable: "Today, 5:10 PM",
    availability: defaultAvailability,
  },
  {
    id: "dr-sato",
    name: "Dr. Haru Sato",
    clinicId: "harbor-derma",
    specialization: "Dermatology",
    languages: ["Japanese", "English"],
    rating: 4.4,
    nextAvailable: "Tomorrow, 1:15 PM",
    availability: defaultAvailability,
  },
  {
    id: "dr-park",
    name: "Dr. Eun Park",
    clinicId: "sakura-ortho",
    specialization: "Orthopedics",
    languages: ["English", "Korean"],
    rating: 4.9,
    nextAvailable: "Tomorrow, 9:40 AM",
    availability: defaultAvailability,
  },
  {
    id: "dr-harrison",
    name: "Dr. Caleb Harrison",
    clinicId: "sakura-ortho",
    specialization: "Sports Medicine",
    languages: ["English", "Spanish"],
    rating: 4.6,
    nextAvailable: "Tomorrow, 11:20 AM",
    availability: defaultAvailability,
  },
  {
    id: "dr-mori",
    name: "Dr. Aya Mori",
    clinicId: "ap-house-family",
    specialization: "General Medicine",
    languages: ["Japanese", "English"],
    rating: 4.3,
    nextAvailable: "Today, 5:20 PM",
    availability: defaultAvailability,
  },
  {
    id: "dr-alvarez",
    name: "Dr. Sofia Alvarez",
    clinicId: "harbor-womens",
    specialization: "Gynecology",
    languages: ["English", "Spanish"],
    rating: 4.8,
    nextAvailable: "Today, 5:50 PM",
    availability: defaultAvailability,
  },
];
